const mongoose = require('mongoose');

const AutoGiftingSchema = new mongoose.Schema({
    user: {
        type: mongoose.Schema.Types.ObjectId,
        ref: 'User',
        required: true
    },
    recipient: {
        name: {
            type: String,
            required: true
        },
        relationship: {
            type: String,
            required: true
        },
        contact: {
            email: String,
            phone: String,
            address: {
                street: String,
                city: String,
                state: String,
                zipCode: String,
                country: String
            }
        },
        socialProfile: {
            platform: String,
            profileUrl: String
        }
    },
    occasion: {
        type: {
            type: String,
            enum: ['birthday', 'anniversary', 'festival', 'achievement', 'random-act', 'custom'],
            required: true
        },
        name: String,
        date: {
            type: Date,
            required: true
        },
        recurring: {
            enabled: Boolean,
            frequency: {
                type: String,
                enum: ['yearly', 'monthly', 'weekly']
            }
        },
        reminderSettings: {
            daysBefore: {
                type: Number,
                default: 7
            },
            reminderMethod: {
                type: [String],
                enum: ['email', 'sms', 'push', 'whatsapp'],
                default: ['email']
            }
        }
    },
    giftPreferences: {
        budget: {
            min: Number,
            max: Number,
            currency: {
                type: String,
                default: 'INR'
            }
        },
        categories: [String],
        avoid: [String],
        personalityTraits: [String],
        interests: [String],
        tone: {
            type: String,
            enum: ['funny', 'emotional', 'formal', 'casual', 'romantic']
        }
    },
    relationshipInsights: {
        lastInteraction: Date,
        interactionFrequency: String,
        appreciationScore: Number,
        forgottenMoments: [{
            date: Date,
            occasion: String,
            missed: Boolean
        }],
        notes: String
    },
    autoGiftSettings: {
        enabled: {
            type: Boolean,
            default: false
        },
        requireApproval: {
            type: Boolean,
            default: true
        },
        defaultBudget: Number,
        preferredCreators: [{
            type: mongoose.Schema.Types.ObjectId,
            ref: 'User'
        }],
        messageTemplate: String
    },
    scheduledGifts: [{
        orderId: {
            type: mongoose.Schema.Types.ObjectId,
            ref: 'Order'
        },
        scheduledDate: Date,
        status: {
            type: String,
            enum: ['pending', 'approved', 'rejected', 'sent', 'failed'],
            default: 'pending'
        },
        gift: {
            type: mongoose.Schema.Types.ObjectId,
            ref: 'Product'
        },
        message: String,
        autoGenerated: Boolean
    }],
    aiSuggestions: [{
        date: Date,
        suggestion: String,
        confidence: Number,
        actedUpon: Boolean
    }],
    createdAt: {
        type: Date,
        default: Date.now
    },
    updatedAt: {
        type: Date,
        default: Date.now
    }
});

AutoGiftingSchema.index({ user: 1, 'occasion.date': 1 });
AutoGiftingSchema.index({ 'occasion.date': 1 });
AutoGiftingSchema.index({ 'autoGiftSettings.enabled': 1 });

module.exports = mongoose.model('AutoGifting', AutoGiftingSchema);
